kafka:
  topics:
    advice: advice-topic

spring:
  main:
    banner-mode: off

  kafka:
    admin:
      client-id: my-admin
    listener:
      ack-mode: MANUAL
      concurrency: 4
    bootstrap-servers:
      localhost:29097
    consumer:
      # A unique string that identifies the consumer group to which this consumer belongs.
      group-id:
        spring-retry-demo-group-5
      # What to do when there is no initial offset in Kafka or if the current offset no longer exists on the server.
      auto-offset-reset:
        latest
      key-deserializer:
        org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer:
        org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit:
        false
      properties:
        spring.json.trusted.packages: '*'
    producer:
      key-serializer:
        org.apache.kafka.common.serialization.StringSerializer
      value-serializer:
        org.apache.kafka.common.serialization.StringSerializer


logging:
  level:
    org.apache.kafka.clients.consumer: FATAL
    org.apache.kafka.clients.producer: WARN
    org.apache.kafka.clients: WARN
    org.apache.kafka.common.utils: WARN

